spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BongGong

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://database-1.c0d1bhka4gti.ap-northeast-2.rds.amazonaws.com:3306/Bonggong?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
      ddl-auto: update


  hikari:
    connectionTimeout: 5000
    vaildationTimeout: 1000
    maxPoolSize: 30

  messages:
    basename: i18n/exception
    encoding: UTF-8




  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    username: 9guyu77@gmail.com
    password: asd019283!
    smtp:
      start-tls-enable: true
      auth: true



paths:
  /email/send:
    post:
      tags:
        - Email APIs
      summary: 입력한 이메일로 인증번호를 요청
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: Gildong.Hong@hancom.com
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
        '400':
          description: Client error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: param-003
                      detail:
                        type: string
                        example: Parameter name mismatch
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: server-001
                      detail:
                        type: string
                        example: Internal server error
  /email/auth:
    post:
      tags:
        - Email APIs
      summary: 이메일과 인증번호를 입력하여 유효한 이메일인지 확인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: Gildong.Hong@hancom.com
                auth:
                  type: string
                  example: 123
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: true
        '400':
          description: Client error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                      detail:
                        type: string
                    example:
                      - code: param-003
                        detail: Parameter name mismatch
                      - code: param-004
                        detail: Email auth error. check the value again
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: server-001
                      detail:
                        type: string
                        example: Internal server error
