spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BongGong

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    username: 9guyu77@gmail.com
    password: asd019283!
    smtp:
      start-tls-enable: true
      auth: true